#!/usr/bin/perl
#---------------------------------------------------------------------
#  $Id: apache.auth.module,v 1.4 1998/11/14 00:07:31 eric Exp $
#
#  eThreads - Threaded forum software for use on the WWW
#  Copyright (C) 1998 Eric Richardson
#
#       This program is free software; you can redistribute it and/or
#       modify it under the terms of the GNU General Public License
#       as published by the Free Software Foundation; either version 2
#       of the License, or (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#       For information on eThreads, contact Eric Richardson at
#       eric@gospelcom.net , or check out the eThreads web site at
#       http://www.ethreads.com
#
#  This is the eThreads module for Apache-based .htaccess file 
#  authentication.  It uses a single database for all users in 
#  all forums.
#
#---------------------------------------------------------------------

sub auth_get_username {
	my $username = $ENV{REMOTE_USER};
	return $username;
}

sub auth_get_userinfo {
	my $username;
	if ($_[0]) {
		$username = shift;
	} else {
		$username = $ENV{REMOTE_USER};
	}
	
	my $dbu = &db_dbu_connect;	

	my $get_userinfo = $dbu->prepare("
		select username,firstname,lastname,email,signature,timestamp 
		from $forum{user_tbl} where username='$username'
	");

	&bail($dbu->errstr) unless ($get_userinfo->execute);

	my %user;

	($user{username},$user{firstname},$user{lastname},$user{email},
	$user{signature},$user{timestamp}) = 
	$get_userinfo->fetchrow_array;

	$get_userinfo->finish;
	$dbu->disconnect;

	return %user;
}

#-------------#
# Change Logs #
#-------------#

# $Log: apache.auth.module,v $
# Revision 1.4  1998/11/14 00:07:31  eric
# * removed un-needed line
#
# Revision 1.3  1998/09/28 23:09:10  eric
# * added auth_get_userinfo
#
# Revision 1.2  1998/09/27 16:48:35  eric
# * renamed subroutine to conform to eThreads authentication module specs.
#
# Revision 1.1  1998/09/25 02:42:10  eric
# * htaccess file based authentication
#

#---------------#
# End of Script #
#---------------#

1;

