#!/usr/bin/perl
#################################################
# $Id: member-post,v 1.4 1998/04/25 16:30:34 eric Exp $
#
#       eThreads - Threaded forum software for the web
#       Copyright (C) 1998 Eric Richardson
#
#       This program is free software; you can redistribute it and/or
#       modify it under the terms of the GNU General Public License
#       as published by the Free Software Foundation; either version 2
#       of the License, or (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#       For information on eThreads, contact Eric Richardson at
#       eric@gospelcom.net , or check out the web site at
#       http://www.ericrichardson.com/e-threads/
#
#	This script is part of the eThreads
#	discussion group software by eSoft. 
#	This script is called by the others to
#	write to the database.
# $Log: member-post,v $
# Revision 1.4  1998/04/25 16:30:34  eric
# Removed local use code, now uses common.pl for that
#
# Revision 1.3  1998/04/22 23:25:45  eric
# Added GPL information to comments
#
# Revision 1.2  1998/04/21 02:39:06  eric
# Added RCS Log Information
#
#################################################

require "common.pl";

$username = $ENV{REMOTE_USER};

&get_vars;
&select_group;

# Get the fullname and email address of the user
$get_user_info = $dbm->prepare("select fullname,email from users where username='$username'");
unless ($get_user_info->execute) {
	&log_error;
}
else {
	($fullname,$email) = $get_user_info->fetchrow_array;
}

# User functions (for members only)
&post_message unless($syntax);
&modify_message_user if($syntax == 10);
&delete_message_user if($syntax == 20);

# Special Administrator Functions (require admin for group)
&modify_message_admin if($syntax == 110);
&delete_message_admin if ($syntax == 120);

print "Location: /e-threads/view?who=$who&syntax=20&id=$replyto\n\n" unless ($replyto == 0);
print "Location: /e-threads/view?who=$who\n\n" if($replyto == 0);
