#!/usr/bin/perl
#########################################################
#       $Id: mSQL.module,v 1.2 1998/06/13 17:24:22 eric Exp $
#
#       eThreads - Threaded forum software for the web
#       Copyright (C) 1998 Eric Richardson
#
#       This program is free software; you can redistribute it and/or
#       modify it under the terms of the GNU General Public License
#       as published by the Free Software Foundation; either version 2
#       of the License, or (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#       For information on eThreads, contact Eric Richardson at
#       eric@gospelcom.net , or check out the web site at
#       http://www.ethreads.com/
#
#	$Log: mSQL.module,v $
#	Revision 1.2  1998/06/13 17:24:22  eric
#	Added GPL info and RCS id and Log.
#
#
########################################################

sub db_connect_dbm {
	$dbm = DBI->connect("DBI:$db_type:$db_main:$db_host");
}

sub db_connect_dbh {
	$dbh = DBI->connect("DBI:$db_type:$db:$db_host");
}

sub db_post_message {
	$get_seq = $dbh->prepare("select _seq from $tbl");
	unless($get_seq->execute) {
		&log_error;
	}
	else {
		$next_id = $get_seq->fetchrow_array;
		if ($username) {
			$post_message = "insert into $tbl(name,email,subject,message,replyto,timestamp,user,id) values('$fullname','$email','$subject','$message',$replyto,$timestamp,'$username',$next_id)";
		}
		else {
			$post_message = "insert into $tbl(name,email,subject,message,replyto,timestamp,id) values('$fullname','$email','$subject','$message',$replyto,$timestamp,$next_id)";
		}
	}
}

sub db_create_table {
	$dbh->do("
			create table $tbl (
			name      char(30),             
			email     char(30),             
			posted    char(20),             
			replyto   int,                  
			id        int,                  
			subject   char(80),             
			message   text(100000),         
			timestamp int,
			user      char(30))
	")
}

sub db_create_index {
	$dbh->do("create unique index idx1 on $tbl (id)")
}

sub db_create_sequence {
	$dbh->do("create sequence on $tbl step 1 value 1")
}

1;
