#!/usr/bin/perl
#---------------------------------------------------------------------
#  $Id: view,v 1.22 2000/06/07 18:14:49 eric Exp $
#
#  eThreads - revolutionizing forums... again.
#  Copyright (C) 1999 Eric Richardson
#
#       This program is free software; you can redistribute it and/or
#       modify it under the terms of the GNU General Public License
#       as published by the Free Software Foundation; either version 2
#       of the License, or (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  
#       02111-1307, USA.
#
#       For information, contact eThreads:
#           ethreads@ethreads.com
#           http://ethreads.com
#
#  This is the un-authenticated viewer script for eThreadsIII.  It 
#  uses eThreads.pm to provide all un-authenticated functionality.
#
#---------------------------------------------------------------------

use eThreads::core;
use eThreads::viewer;
use strict;
use vars qw($viewer $core %e $db $m_db %posts %input);

$e{functions}{login}{redirect} = 1;

$core = eThreads::core->start(
	script		=> "view",
	browse_root	=> 1,
);

$viewer = eThreads::viewer->start();

#---------#
# Routing #
#---------#

if ($e{status}{sidetrack}) {
	# do nothing...  absolutely nothing.
} else {
	$core->function_finder;
}

#-------------#
# Subroutines #
#-------------#

sub signup {
	$core->header("Sign Up for Authenticated Viewing");
	my $error;

	if ($input{uname}) {
		$error = 1 unless ($input{pass1} eq"$input{pass2}");
		
		my $check_for_duplicates = $m_db->prepare("
			select username from $e{settings}{db}{tbls}{users} where username='$input{uname}'
		");
		$core->bail(0,$m_db->errstr) unless ($check_for_duplicates->execute);
		$error = 2 if ($check_for_duplicates->rows);
	}

	if (!$input{uname} || $error) {
		if ($error == 1) {
			print qq(<b>Your passwords do not match.  Please try again.</b><p>);
		} elsif ($error == 2) {
			print qq(<b>The username you selected is in use.  Please select another.</b><p>);
		}

		print <<EOP;
		This forum utilizes the <b>$e{settings}{db}{users_ident}</b>.  If you have 
		signed up at another forum displaying this identifier your username is already valid 
		for this forum.  Please go ahead and log in.
		<p>
		Please select a username and password you would like to use to access 
		this forum.
		<p><form action="$e{forum}{path}/$e{script}/$input{forum}/signup" method=post>
		Username: <input type=text name=uname value='$input{uname}' size=20>
		<br>Password (2x): <input type=password name='pass1' size=10>
		<input type=password name='pass2' size=10>
		<p>Name: <input name='name' size=30 value='$input{name}'>
		<br>email: <input name='email' size=20 value='$input{email}'>
		<br>Submit: <input type=submit value='Sign Up'>
EOP
	} else {
		my $pass = crypt($input{pass1},$input{uname});
		require "module.auth.$e{settings}{d_auth}";
		&auth::signup('',$input{uname},$pass,$input{name},$input{email});
		print <<EOP;
		Your username, <i>$input{uname}</i>, has been created.  
		<a href="$e{forum}{path}/$e{settings}{scripts}{members}/$input{forum}/">Login Here</a>.
EOP
	}

	$core->footer;
}

#----------

sub main_menu {
	$core->header();

	if ($input{drop} eq"all") {
		$core->get_posts(2);
	} else {
		$core->get_posts(0,0);
	}
	
	print <<EOP if ($e{forum}{intro});
	$e{forum}{intro}
	<p>
EOP
	$viewer->thread_table_top;
	$viewer->print_threads(0,1,0);
	$viewer->thread_table_bottom;

	$core->buttons("top");


	$core->footer;
}

#----------

sub view_post {

	my %post = $core->get_post($input{id});
	$core->header("$e{language}{view_post}: $post{title}");

	$viewer->view_post("","",%post);

	print "<p>";
	$core->buttons("post",$post{child_of});
	print "</p>";

	if ($post{children}) {
		$core->get_posts(0,$input{id});
		$viewer->thread_table_top;
		$viewer->print_threads($input{id},1,0);
		$viewer->thread_table_bottom;
	}
	$core->footer;
}

#----------

sub post {
	if ($input{preview}) {
		$core->header("Posting '$input{title}':");
		$viewer->preview_post;
		$core->footer;
	} elsif ($input{submit}) {
		$core->header("Previewing '$input{title}':");
		$viewer->post;
		$core->footer;
	} else {
		$core->header("Compose Post");
		$viewer->compose_post;
		$core->footer;
	}
}

#-------------#
# Change Logs #
#-------------#

# $Log: view,v $
# Revision 1.22  2000/06/07 18:14:49  eric
# * glomule creation fixes
# * glomule deletion fixes
# * fixed all old references to presets
# * domain rooting work
# * glomule module work
# * assorted other fixes
#
# Revision 1.21  2000/06/06 00:01:15  eric
# * finished integrating look classes and the preset_headers/preset_data
#
# Revision 1.20  2000/05/01 21:10:57  eric
# * a little domain rooting work
# * some fixes for Netscape's sucky CSS handling
#
# Revision 1.19  2000/04/29 16:39:19  eric
# * merging eThreads1_2-devel tree back into main eThreads tree
#
# Revision 1.17.4.8.4.10  2000/04/22 20:31:06  eric
# * work on the domain rooting code
# * added the glomule::disable_buttons sub to the rest of the glom types
# * added a '</form>' whose absense was dorking up picky CSS
#
# Revision 1.17.4.8.4.9  2000/04/11 01:12:11  eric
# * merging changes after apparently doing some CVS screwing up...
#
# Revision 1.17.4.8.4.8  2000/03/12 00:54:19  eric
# * ported invitation only glomule to new structure
#
# Revision 1.17.4.8.4.7  2000/02/23 06:51:25  eric
# * ummm...  i did stuff.  lots of stuff.
#
# Revision 1.17.4.8.4.6  2000/02/22 20:58:11  eric
# * rewrote core::start function and changed arg style
# * wrote forum finder
# * redid browse_child_forum backend to be generic
#
# Revision 1.17.4.8.4.5  2000/02/21 19:09:02  eric
# * updated user information to use new user tbl structure
#
# Revision 1.17.4.8.4.4  2000/01/17 22:39:29  eric
# * message preview is now functional
#
# Revision 1.17.4.8.4.3  1999/12/22 21:28:51  eric
# * drop to new posts now works
# * renamed router function to function_finder
#
# Revision 1.17.4.8.4.2  1999/12/22 18:41:14  eric
# * new post code
# * schema work
#
# Revision 1.17.4.8.4.1  1999/09/27 23:22:25  eric
# * started changeover to new forum name system
# * started changeover to new function calling system
#
# Revision 1.17.4.8  1999/09/03 12:25:04  eric
# * rolled $u_db into $m_db
#
# Revision 1.17.4.7  1999/08/26 14:04:25  eric
# * updated all headers to conform to standard eThreads header
#
# Revision 1.17.4.6  1999/08/18 07:43:46  eric
# * finally fixed the last of the $e{forum}{user_tbl} linger calls...  how
#   did those stay around so long?
# * members:   code for unsubscribe and manage_email
# * viewer.pm: code to call instamailer when post made
#
# Revision 1.17.4.5  1999/08/18 07:03:36  eric
# * moved signup code from view to auth module
# * added auth module for mod_auth
#
# Revision 1.17.4.4  1999/08/18 06:30:53  eric
# * forum_type modules and code
# * first revision of instamailer (subscription notifier)
# * some subscription code in members
#
# Revision 1.17.4.3  1999/06/24 22:38:48  eric
# * test pointer to search code
#
# Revision 1.17.4.2  1999/06/22 20:02:18  eric
# * fixes for invitation only forums
#
# Revision 1.17.4.1  1999/06/22 14:37:34  eric
# * added support for password protected forums
#
# Revision 1.17  1999/05/06 23:06:39  eric
# * removed old table close from main_menu
# * converted child display in view_post to new format
#
# Revision 1.16  1999/04/15 00:43:36  eric
# * fixed old broken print_threads call in view_post
#
# Revision 1.15  1999/04/13 23:15:12  eric
# * added blurb about user database in signup code
#
# Revision 1.14  1999/04/09 06:23:25  eric
# * pointer to print_profile
# * pointer to posts_by_user
#
# Revision 1.13  1999/04/07 02:43:24  eric
# * added signup code
#
# Revision 1.12  1999/04/06 21:32:07  eric
# * abstracted thread display table structure to look theme
#
# Revision 1.11  1999/03/26 17:55:35  eric
# * updated print_threads call to conform to new syntax
#
# Revision 1.10  1999/03/23 23:10:49  eric
# * language updates
#
# Revision 1.9  1999/03/22 00:43:38  eric
# * added login code (pointer to auth module)
# * moved content-type to core
#
# Revision 1.8  1999/02/27 21:01:23  eric
# * moved core->start from viewer to view and added argument to pass
#   $core into viewer
#
# Revision 1.7  1999/02/27 17:44:08  eric
# * fixed call to bad_function wording
# * tweaks to conform to new $viewer->view_post syntax
#
# Revision 1.6  1999/02/19 20:54:18  eric
# * post stuff
# * fix to button_bar(post) thing to pass post info in
#
# Revision 1.5  1999/02/09 22:04:05  eric
# * various changes in adding eThreads::viewer compatibility
#
# Revision 1.4  1999/01/20 22:32:07  eric
# * added test for drop=all
# * added pointers to buttons
#
# Revision 1.3  1999/01/20 21:25:46  eric
# * added code for viewing posts
#
# Revision 1.2  1999/01/20 19:51:45  eric
# * added {status}{sidetrack} stuff
# * added hooks for printing threads
#
# Revision 1.1  1999/01/20 16:52:21  eric
# * shell of viewer script
# * prints header and footer using eThreads.pm
#

#---------------#
# End of Script #
#---------------#
